<?php

/**
 * @file
 * Controls whos.amung.us blocks.
 */

/**
 * Implements hook_permission().
 */
function whos_amung_us_permission() {

  return array(
    'administer whos_amung_us blocks' => array(
      'title' => t('Administer whos.amung.us blocks'),
    ),
  );

}

/**
 * Implements hook_theme().
 */
function whos_amung_us_theme() {

  return array(
    'whos_amung_us' => array(
      'variables' => array(
        'widget' => 'general',
        'options' => array(),
        'id' => 'whos_amung_us',
      ),
      'file' => 'includes/whos_amung_us.theme.inc',
    ),
  );

}

/**
 * Loads a whos.amung.us custom block.
 *
 * @param string $name
 *   The unique whos.amung.us block machine name.
 *
 * @return array
 *   A fully-loaded whos.amung.us block upon successful load,
 *   or NULL if it can't be loaded
 */
function whos_amung_us_item_load($name) {

  $sql = db_select('whos_amung_us_block', 'b')
    ->fields('b')
    ->condition('machine_name', $name)
    ->execute();

  if ($row = $sql->fetchAssoc()) {
    return $row;
  }
  return NULL;

}

/**
 * Implements hook_menu().
 */
function whos_amung_us_menu() {

  $items = array();
  $items['admin/structure/block/add-whos-amung-us-block'] = array(
    'title' => 'Add whos.amung.us block',
    'description' => 'Add a new whos.amung.us block.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whos_amung_us_configuration_new_form'),
    'access arguments' => array('administer whos_amung_us blocks'),
    'file' => 'includes/whos_amung_us.admin.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/services/whos-amung-us'] = array(
    'title' => 'Whos.amung.us',
    'description' => 'Whos.amung.us default options',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('whos_amung_us_configuration_config_form'),
    'access arguments' => array('administer whos_amung_us blocks'),
    'file' => 'includes/whos_amung_us.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;

}

/**
 * Implements hook_block_info().
 */
function whos_amung_us_block_info() {

  $blocks = array();
  $sql = db_select('whos_amung_us_block', 'b')
    ->fields('b', array('bid', 'info', 'machine_name'))
    ->execute();
  while ($row = $sql->fetchAssoc()) {
    $blocks[$row['machine_name']] = array(
      'info' => t($row['info']),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    );
  }
  return $blocks;

}

/**
 * Implements hook_block_view().
 */
function whos_amung_us_block_view($delta = '') {

  $block['subject'] = '';
  $block['content'] = whos_amung_us_load_render($delta);
  return $block;

}

/**
 * Implements hook_block_configure().
 */
function whos_amung_us_block_configure($delta = '') {

  module_load_include('inc', 'whos_amung_us', 'includes/whos_amung_us.admin');
  return _whos_amung_us_block_configure($delta);

}

/**
 * Implements hook_block_save().
 */
function whos_amung_us_block_save($delta = '', $edit = array()) {

  module_load_include('inc', 'whos_amung_us', 'includes/whos_amung_us.admin');
  _whos_amung_us_block_save($delta, $edit);

}

function whos_amung_us_name_exists($name) {

  $item = whos_amung_us_item_load($name);
  if ($item) {
    return TRUE;
  }
  else {
    return FALSE;
  }

}

function whos_amung_us_load_render($name) {

  $item = whos_amung_us_item_load($name);
  if ($item) {
    return whos_amung_us_render($item);
  }
  return '';

}

function whos_amung_us_render($item) {

  if (!is_array($item['config'])) {
    $conf = unserialize($item['config']);
  }
  else {
    $conf = $item['config'];
  }
  $conf += whos_amung_us_default_form_values();
  return theme(
    'whos_amung_us',
    array(
      'widget' => $conf['widget'],
      'options' => $conf,
      'id' => 'rnd' . $item['bid'],
    )
  );

}

function whos_amung_us_default_form_values() {

  return array(
    'name' => '',
    'mname' => '',
    'widget' => 'general',
    'foreground' => 'ffc20e',
    'background' => '000000',
    'position' => 'left-middle',
    'map' => 'natural',
    'marker' => 'star-blue',
    'width' => '420',
    'height' => '210',
  );

}
